# Pareto Shell Analysis

For multi-objective problems it is often useful to find the "Parto Front". If some hypothesis x1 is preferble to some other hypothesis x2 across every objective function, it's obviously not sensible to ever suggest x2 if we have the option to do x1. We say x1 "Pareto dominates" x2. 

The set of points which are not Pareto dominated by anything in are the "Pareto front" or the "first Pareto shell", and the set of points not dominated by anything not in the Nth Pareto shell are the (N+1)th Pareto shell.

In [1]:
import numpy as np

Generating some random data to play around with. Replace this with the actual objective function values of the data you wish to analyze. Note that this code assumes you are maximising, so multiply aby objectives which must be minimized by -1 before pasing.

In [2]:
testData = np.random.randint(1, 101, size = (50, 4))
print(testData)

[[ 32  64  58  39]
 [ 95  16  14  16]
 [ 56  65  71   7]
 [ 50  60  63  91]
 [ 39   5  72  13]
 [ 96  80   4  79]
 [ 10   6  41  98]
 [ 26  25  52  43]
 [ 39   9  50 100]
 [ 72   5  69  96]
 [ 26  93  41   9]
 [  3  21  56  63]
 [ 82  66  76  16]
 [ 11  69  13  84]
 [ 47  92  32  25]
 [ 54   5  71  89]
 [ 50  15  35  82]
 [ 40  18  28  19]
 [ 62  29  87  99]
 [ 86  14  34  43]
 [ 32  45  71  37]
 [ 90  58  69  35]
 [ 22  41  66  87]
 [ 14  88   5  54]
 [ 97  99  23  94]
 [ 71   1   7  61]
 [ 50  76 100  41]
 [ 13  61  89  32]
 [ 33  62  71  60]
 [ 42  55  91  54]
 [ 88  63  88  93]
 [  3  64  79  35]
 [ 74  89   5  14]
 [ 83  83  42  23]
 [ 29  94  52  71]
 [ 98  33   5  29]
 [ 35  82  77  88]
 [ 71  88  88  42]
 [ 55  66  65  94]
 [ 70  79  68   7]
 [ 93  37  18  24]
 [ 54  48  96  55]
 [ 63  32  36  68]
 [  1  35  20   2]
 [100  19  43  19]
 [ 23  80  80  96]
 [ 25  34  30  44]
 [ 39  55  71  73]
 [ 74  55  25  20]
 [ 37  19  46  61]]


In [3]:
class ParetoShell:
    def __init__(
        self,
        data,
    ):
        self.data = [tuple(x) for x in data]
        self.shells = []
    #True if x1 dominates x2, false otherwise
    def paretoDominates(self, x1, x2):
        x1BetterSomewhere = False
        for i in range(len(x1)):
            if x2[i] > x1[i]:
                return(False)
            if x2[i] < x1[i]:
                x1BetterSomewhere = True
        return(x1BetterSomewhere)
    #Finds the next Pareto shell, and strips it from self.data
    def findNextShell(self):
        shell = []
        for x1 in self.data:
            getsDominated = False
            for x2 in self.data:
                if self.paretoDominates(x2, x1):
                    getsDominated = True
            if not getsDominated:
                shell.append(x1)
        self.shells.append(shell)
        self.data = [x for x in self.data if x not in shell]
        return(shell)
    #Find all the shells
    def findAllShells(self):
        while len(self.data) != 0:
            self.findNextShell()
        return(self)
    def printParetoFront(self):
        print(f"The Pareto front is: {self.findAllShells().shells[0]}")
    #Print Nth shell
    def printNthShell(self, n):
        self.findAllShells()
        print(self.shells[n])
        return(self)
        
ps = ParetoShell(testData)
ps.printParetoFront()

The Pareto front is: [(np.int64(39), np.int64(9), np.int64(50), np.int64(100)), (np.int64(72), np.int64(5), np.int64(69), np.int64(96)), (np.int64(82), np.int64(66), np.int64(76), np.int64(16)), (np.int64(47), np.int64(92), np.int64(32), np.int64(25)), (np.int64(62), np.int64(29), np.int64(87), np.int64(99)), (np.int64(90), np.int64(58), np.int64(69), np.int64(35)), (np.int64(97), np.int64(99), np.int64(23), np.int64(94)), (np.int64(50), np.int64(76), np.int64(100), np.int64(41)), (np.int64(42), np.int64(55), np.int64(91), np.int64(54)), (np.int64(88), np.int64(63), np.int64(88), np.int64(93)), (np.int64(83), np.int64(83), np.int64(42), np.int64(23)), (np.int64(29), np.int64(94), np.int64(52), np.int64(71)), (np.int64(98), np.int64(33), np.int64(5), np.int64(29)), (np.int64(35), np.int64(82), np.int64(77), np.int64(88)), (np.int64(71), np.int64(88), np.int64(88), np.int64(42)), (np.int64(55), np.int64(66), np.int64(65), np.int64(94)), (np.int64(54), np.int64(48), np.int64(96), np.int64