# Objectives

Some problems involve rearranging a fixed set of objects. Any such problems go here.

In [1]:
import random as r
import numpy as np

## Random Search

In [2]:
class RandomSearch:
    def __init__(
        self,
        N
    ):
        self.N = N
        
    def generateRandomHypothesis(self):
        output = [c for c in range(self.N)]
        r.shuffle(output)
        return(output)
    
    def optimize(self,
                objectiveFunction,
                numIterations = 25000):
        bestX = None
        bestY = -float("inf")
        for i in range(numIterations):
            newX = self.generateRandomHypothesis()
            newY = objectiveFunction(newX)
            if newY > bestY:
                bestX = newX
                bestY = newY
        return(bestX)

## Dinner Table Problem

Suppose you have N coworkers and a matrix where the ijth element tells you how much person i likes person j. Then, we must seat all these people around a circular table. So the utility of the ordering is the sum of the matrix values for adjacent people.

In [3]:
N = 15
friendshipMatrix = np.random.randint(-10, 11, size = (N, N))
print(friendshipMatrix)

def seatingValue(x):
    output = friendshipMatrix[0][-1] + friendshipMatrix[-1][0]
    output += sum(friendshipMatrix[x[i]][x[i + 1]] + friendshipMatrix[x[i + 1]][x[i]] for i in range(len(x) - 1))
    return(output)

rs = RandomSearch(N)
arrangement = rs.optimize(seatingValue, numIterations = 10 ** 3)
print("Chosen arrangement:", arrangement)
print("Average friendliness in arrangement", seatingValue(arrangement) / N)

[[ -3   7   5  -6   6   1   6   7  10   3  -6  -6   1   4  -6]
 [ -5   1  -7   5   3   2   1   8   8   0   8  -2  -9  -8   0]
 [ -6  10  -9  -3   6  -5  10 -10  -3  -2  -5   6 -10   6   9]
 [  0   4  -6   3  -7  -3   1   5  -4   7  -6   2  -5  -8  -3]
 [ -4   9  -1   0  -9   2  -3   6   0   7  -6  -5  -8  10  10]
 [  6   6  -6   0   0  -6   3  -7  -9   0  -1   0  -1  10   5]
 [-10   2   7  -3   2  -1   4   6  -3   2  -1  -8  -2  -6   4]
 [ -9  -3  -2   8  -6  -5   0   2   5  10  10   6   8   9  -5]
 [ -9   7  -5  -3   1   9   6  -1  -9  -4   1  -7  -8  10   2]
 [ -9   3   2   5  10  -8  -2  -6 -10  -3   8   3   8   7   2]
 [  5   4   0  -8 -10  -4 -10  -2   0   0   9  -5 -10  -3   5]
 [  5  -4  10   7   7  -9   8  -9   2   1   0  -4   6  -7  -4]
 [  8  -4  -5   5  -8  -4  -5   5   5  -7   4   3   9   6  -6]
 [  5   6   1  -4  -1  -4   7  -5  -2   2  -6   3  -2  -2   2]
 [ -7 -10  -7   3   4  -2  -6   5  10   7   4   1  -9  -6  -2]]
Chosen arrangement: [8, 1, 4, 14, 2, 6, 9, 3, 12, 7, 0